#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Values are staged in .env.band (matches the repo's .gitignore `.env.*` rule)
# so a re-run can offer what you already pasted. The final stage renders them
# into agent_config.yaml, which is the file the Band SDK actually reads.
ENV_FILE=".env.band"
CONFIG_FILE="agent_config.yaml"

if [[ ! -f package.json || ! -d sentinel ]]; then
  printf '\n  Run this from the cleanroom repo root (where package.json and sentinel/ live).\n\n'
  exit 1
fi

banner "Band agents — cleanroom specialist + exporter"

# ── Stage 1: account + pro month ──────────────────────────────────────────
stage "Band account"
say "Sign in to Band. If the account is new, redeem the hackathon pro code."
open_url "https://app.band.ai"
step "Sign in (or sign up)."
step "If prompted for a promo/upgrade code, enter: HACKBANDAUG26"
note "Redemption flow is undocumented — if it isn't offered, skip it and keep going."
note "Stuck? Band Discord: https://discord.com/invite/5YkNXmYfjk"
pause "Signed in? Press Enter."

# ── Stage 2: specialist agent ─────────────────────────────────────────────
stage "Specialist agent"
say "This is the agent that issues Dispositions on Consultations (ADR 0001:"
say "it only ever sees metadata, never raw transcript text)."
open_url "https://app.band.ai/agents"
step "Click the 'Connect Remote Agent' button (NOT 'New Agent' — the label changed)."
step "Name it: cleanroom-specialist, and give it any description."
warn "The API key is shown ONCE in a popup. Copy it before closing the dialog."
ask_secret BAND_SPECIALIST_API_KEY "Paste the specialist API key:"
step "Open the agent's Settings page and copy its UUID (agent id)."
ask BAND_SPECIALIST_AGENT_ID "Paste the specialist agent id (UUID):"
write_env BAND_SPECIALIST_API_KEY "$BAND_SPECIALIST_API_KEY"
write_env BAND_SPECIALIST_AGENT_ID "$BAND_SPECIALIST_AGENT_ID"

# ── Stage 3: exporter agent ───────────────────────────────────────────────
stage "Exporter agent"
say "The exporter lives IN the room and acts on @mention — that's what makes"
say "the fail-closed gate structural (ADR 0003): remove the room, export stops."
open_url "https://app.band.ai/agents"
step "'Connect Remote Agent' again. Name it: cleanroom-exporter"
warn "Again: copy the API key from the popup before closing it."
ask_secret BAND_EXPORTER_API_KEY "Paste the exporter API key:"
step "Open that agent's Settings page and copy its UUID (agent id)."
ask BAND_EXPORTER_AGENT_ID "Paste the exporter agent id (UUID):"
write_env BAND_EXPORTER_API_KEY "$BAND_EXPORTER_API_KEY"
write_env BAND_EXPORTER_AGENT_ID "$BAND_EXPORTER_AGENT_ID"

# ── Stage 4: the room ─────────────────────────────────────────────────────
stage "Consultation room"
say "Rooms are under 'Chats' in Band's UI — there's no room API, so this is manual."
open_url "https://app.band.ai"
step "Open 'Chats' in the left nav, then create a room. Name it: cleanroom-consults"
step "Open the participants panel and add BOTH agents"
step "  (cleanroom-specialist and cleanroom-exporter)."
step "Copy the room id out of the URL while the room is open."
note "Agents only see messages that @mention them — that's the routing model."
ask BAND_ROOM_ID "Paste the room id:"
write_env BAND_ROOM_ID "$BAND_ROOM_ID"

# ── Stage 5: SDK ──────────────────────────────────────────────────────────
stage "Band SDK"
say "band-sdk 1.6.0 connects those agents to the room. Installs into .venv-band"
say "so it can't collide with anything else on this machine."
note "Package is band-sdk; the import is 'band'. Needs Python >= 3.11."
warn "Your system Python is $(python3 --version 2>&1 | cut -d' ' -f2) — if wheels aren't built for it,"
warn "the install fails here. That's a packaging problem, not your setup."
if confirm "Create .venv-band and install band-sdk[anthropic]?"; then
  if python3 -m venv .venv-band && ./.venv-band/bin/pip install --quiet --upgrade pip \
     && ./.venv-band/bin/pip install "band-sdk[anthropic]"; then
    printf '  %s✓ installed%s band-sdk[anthropic] into .venv-band\n' "$GREEN" "$RESET"
    note "Activate with: source .venv-band/bin/activate"
  else
    SKIPPED+=('band-sdk install (retry on Python 3.12: python3.12 -m venv .venv-band)')
    warn "install failed — most likely no wheel for this Python. Try 3.12."
  fi
else
  SKIPPED+=('pip install "band-sdk[anthropic]"')
fi

# ── Stage 6: write agent_config.yaml ──────────────────────────────────────
stage "Write $CONFIG_FILE"
say "Rendering the four credentials into the file the SDK reads."
if [[ -f "$CONFIG_FILE" ]] && ! confirm "$CONFIG_FILE exists — overwrite it?"; then
  SKIPPED+=("writing $CONFIG_FILE (kept the existing one; values are in $ENV_FILE)")
  warn "kept the existing $CONFIG_FILE"
else
  # Shape is exactly what band.config.load_agent_config("<key>") expects:
  # top-level agent name -> { agent_id, api_key }. Nothing else at top level,
  # so the room id and URLs stay in .env.band instead.
  cat > "$CONFIG_FILE" <<YAML
# cleanroom — Band agent credentials. GITIGNORED. Never commit this file.
# Written by band-setup.sh on $(date -Iseconds)
specialist:
  agent_id: "$BAND_SPECIALIST_AGENT_ID"
  api_key: "$BAND_SPECIALIST_API_KEY"
exporter:
  agent_id: "$BAND_EXPORTER_AGENT_ID"
  api_key: "$BAND_EXPORTER_API_KEY"
YAML
  chmod 600 "$CONFIG_FILE"
  printf '  %s✓ wrote%s %s (mode 600)\n' "$GREEN" "$RESET" "$CONFIG_FILE"
fi

if git check-ignore -q "$CONFIG_FILE" && git check-ignore -q "$ENV_FILE"; then
  printf '  %s✓ verified%s both files are gitignored\n' "$GREEN" "$RESET"
else
  warn "NOT gitignored — do not commit. Check .gitignore before any git add."
fi
# ──────────────────────────────────────────────────────────────────────────

finish
